spring:
  datasource:
    url: jdbc:postgresql://pg-27c04cdb-gorkem-postgre.i.aivencloud.com:11343/Tivibu
    username: avnadmin
    password: AVNS_y1JoeiXfyMFZO9RqGM4
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: gorkembedel4@gmail.com
    password: stdxeztmfhdxyunz
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true


server:
  port: 8083


