spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/tivibu
    username: gorkem
    password: gorkem
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081