spring:
  datasource:
    url: jdbc:postgresql://pg-27c04cdb-gorkem-postgre.i.aivencloud.com:11343/Tivibu
    username: avnadmin
    password: AVNS_y1JoeiXfyMFZO9RqGM4
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083