apiVersion: v1
kind: Secret
metadata:
  name: tivibu-secret
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcGctMjdjMDRjZGItZ29ya2VtLXBvc3RncmUuaS5haXZlbmNsb3VkLmNvbToxMTM0My9UaXZpYnU=
  SPRING_DATASOURCE_USERNAME: YXZuYWRtaW4=
  SPRING_DATASOURCE_PASSWORD: QVZOU195MUpvZWlYZnlNRlpPOVJxR000